name: before_publish_cli
version: 1.0.2
description: Change Application's name, package name, icon and Splash in one shot.
repository: https://github.com/moohammed-gaber/before_publish_flutter_cli
executables:
  before_publish:

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dartz: ^0.10.0
  dcli: ^1.13.6
  plain_optional: ^1.0.0
  process_run: ^0.12.2+2
  pub_api_client: ^2.1.1
  pubspec_yaml: ^3.1.0
  yaml: ^3.1.0
