name: analysis_options_cli_generator
version: 1.0.4
description: A CLI tool for generating best collection of analysis options rules.
repository: https://github.com/MoGaaber/analysis_options_cli_generator

dependencies:
  dcli: ^1.8.2
  plain_optional: ^1.0.0
  process_run: ^0.12.2
  pub_api_client: ^2.1.1
  pubspec_yaml: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.4

environment:
  sdk: ">=2.14.0 <3.0.0"

executables:
  aog:
